[tool.ruff]
extend-select = ["A", "B", "C4", "I", "N", "D", "S", "T20", "INP", "SIM", "ERA", "RUF"]
line-length = 119
target-version = "py38"
ignore = ["F403", "D104", "D100", "D101", "D102", "D103", "D107", "D211", "D213", "N803", "N806", "N812", "S101", "S301"]

[tool.ruff.pydocstyle]
convention = "google"

[tool.ruff.per-file-ignores]
"__init__.py" = ["E402"]
"config.py" = ["E501"]