version: '3'

services:
  bikeguessr_pipeline:
    container_name: bikeguessr
    build: .
    volumes:
      - ./docker_data/data:/app/docker_data/data
      - ./docker_data/cache:/app/cache
      - ./docker_data/logs:/app/logs
  tensorboard:
    image: tensorflow/tensorflow:latest
    volumes:
      - ./docker_data/logs:/logs
    command: tensorboard --logdir /logs --host 0.0.0.0 --port=6006
    ports:
      - "6006:6006"